name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.15
  audioplayers: ^6.5.1
  google_sign_in: ^6.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  file_picker: ^8.1.2
  path_provider: ^2.0.15
  archive: ^3.3.7
  http: ^1.1.0
  geolocator: ^11.0.0
  flutter_map_location_marker: ^8.1.0
  flutter_image_compress: ^2.1.0
  permission_handler: ^11.3.0
  url_launcher: ^6.3.0
  table_calendar: ^3.0.8

 

  # ---------- OPTIONAL PACKAGES ----------
  # Uncomment when needed:
  # dio: ^5.3.2
  # tflite_flutter: ^0.10.2
  # tflite_flutter_helper: ^0.4.0
  # geocoding: ^3.0.0
  # flutter_map_tile_caching: ^9.0.0
  # flutter_map_marker_cluster: ^1.0.3
  # ---------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/langs/languages.json
    
